ktor:
    application:
        modules:
            - com.nazar.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  domain: "https://nazar.app"
  audience: "janta"
  realm: "Nazar APP"
  secret: "ye raaz ki baat hai" # Secret overriden by environment variable
  issuer: "nazar"
#  connectionString: "mongodb://localhost:27017"
